# frozen_string_literal: true

source 'https://rubygems.org'

gem 'octokit', '~> 4.9.0'
gem 'parallel', '~> 1.12.1'
gem 'ruby-progressbar', '~> 1.9.0'

group :test do
  gem 'cucumber', '~> 3.1.0'
  gem 'mocha', '~> 1.5.0'
  gem 'rspec', '~> 3.7.0'
end
