#!/bin/bash

set -e

cd ruby

IMAGE_ID=`docker build --quiet .`

# Don’t add -t to the below; it causes lines to be output with CRLF separators
docker run --rm -e GITHUB_ORG -e GITHUB_TOKEN $IMAGE_ID ruby -Isrc scripts/list.rb "$@"
