#!/bin/bash

set -e

cd ruby

IMAGE_ID=`docker build --quiet .`

# The -i is required for the progress bar to work
docker run -i --rm -e GITHUB_ORG -e GITHUB_TOKEN $IMAGE_ID ruby -Isrc scripts/unsubscribe.rb "$@"
